<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buy a bottle of singleton_destroy</name>
   <tag></tag>
   <elementGuidId>9acb7b2a-c0c6-4628-9ae6-4ad481a7e738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > div.view > button.destroy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='root']/main/ul/li[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>123b9eef-d44d-4e4a-adb1-4624ba7acb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>destroy</value>
      <webElementGuid>48e6b409-2efc-4fb4-bc59-ba0494b2a1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>todo-item-button</value>
      <webElementGuid>bd27cb58-be13-4a4f-b900-b9c297392402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main&quot;]/ul[@class=&quot;todo-list&quot;]/li[2]/div[@class=&quot;view&quot;]/button[@class=&quot;destroy&quot;]</value>
      <webElementGuid>b90c6b82-6e06-43b3-b234-949b038deac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='root']/main/ul/li[2]/div/button</value>
      <webElementGuid>610fa928-7fbd-4422-99a5-2d8c0aab33cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/button</value>
      <webElementGuid>9efd1568-8598-4cee-8995-433555ae38e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
