<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_todos_todo-input</name>
   <tag></tag>
   <elementGuidId>97e4be7a-a1fd-4a70-829b-5d9690b04cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#todo-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='todo-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6739f507-b37a-41f6-8178-2e969616aa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new-todo</value>
      <webElementGuid>b80a0806-4a30-44ef-98be-91cc7bf4510a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>todo-input</value>
      <webElementGuid>1d336158-38d2-459b-bc0c-d6c31db850f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0721dc7a-9309-4ae5-9959-d8d60574d841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>05b14f16-2da3-431e-a77f-fc813f61dab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What needs to be done?</value>
      <webElementGuid>49a13e92-6098-489e-b2cd-8ec744981360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;todo-input&quot;)</value>
      <webElementGuid>afc83edf-1b9a-453e-9ef3-fbfc9271dd8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='todo-input']</value>
      <webElementGuid>f91cc6af-24c4-490f-a038-97bd782fb0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='root']/header/div/input</value>
      <webElementGuid>14cd9c2d-f781-48c1-b40c-1117ef194467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6f68a0f7-017b-4e4e-a21b-8a4b9e001bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'todo-input' and @type = 'text' and @placeholder = 'What needs to be done?']</value>
      <webElementGuid>d65ab660-b17a-4cc0-a239-8c08a99a2710</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
